# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2421839374076f51b7b4b00f5a908f0b07e48c75741cb05758d821e838fe7b97afeee359d56cecf31efb5d67f7b81717a67cfaa573aa7aa88d85cfb7ef9a986

test:
  secret_key_base: 6a1cc67a29d8d0d2792667513c32b4a626af538858ca4871e92c429b4018a7be8bfdffb74892d87aa036300a83a1c9595056daefa048750f4951098550d5a8cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
